name: Deploy Game

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Game
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Install and Build
        run: yarn && yarn deploy

      - name: Publish Folder
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: build
          folder: builds/1.0
